---

- name: "SECTION | 1.1 | Ensure packages are obtained from authorized repositories"
  ansible.builtin.import_tasks: cis_1.1.yml

- name: "SECTION | 1.2 | Ensure systemd Service Files Are Enabled"
  ansible.builtin.import_tasks: cis_1.2.yml

- name: "SECTION | 1.3 | Ensure Data Cluster Initialized Successfully"
  ansible.builtin.import_tasks: cis_1.3.yml
